### ISSUE TITLE
Singularity h2a_glm_fm_excl_triplet_item

### ISSUE THREAD

**Issue by behinger** [behinger/project-ocd#6]
> Für Hypothese 2a (RT) gibt es für das beste Modell (h2a_glm_fm_excl_triplet_item) trotzdem noch Singularity warnings. Würdest du hier dann noch die random slopes für stim_ocd/pho/neg rausnehmen?

Erstmal würde ich die correlations rausnehmen (zerocorr / `||`) - dann die random slopes die nichts mit unserer Hypothese zu tun haben

**Comment by celinalianemueller** [comment]
Perfekt, das hat das singularity issue gelöst, danke!
